In [5]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
arr1=np.array([[1,2,3],
            [4,5,6],
           [7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr2=np.zeros((5,4,3))
print(arr2)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr3=np.arange(1,12)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [11]:
arr4=np.linspace(1,10,79)
print(arr4)

[ 1.          1.11538462  1.23076923  1.34615385  1.46153846  1.57692308
  1.69230769  1.80769231  1.92307692  2.03846154  2.15384615  2.26923077
  2.38461538  2.5         2.61538462  2.73076923  2.84615385  2.96153846
  3.07692308  3.19230769  3.30769231  3.42307692  3.53846154  3.65384615
  3.76923077  3.88461538  4.          4.11538462  4.23076923  4.34615385
  4.46153846  4.57692308  4.69230769  4.80769231  4.92307692  5.03846154
  5.15384615  5.26923077  5.38461538  5.5         5.61538462  5.73076923
  5.84615385  5.96153846  6.07692308  6.19230769  6.30769231  6.42307692
  6.53846154  6.65384615  6.76923077  6.88461538  7.          7.11538462
  7.23076923  7.34615385  7.46153846  7.57692308  7.69230769  7.80769231
  7.92307692  8.03846154  8.15384615  8.26923077  8.38461538  8.5
  8.61538462  8.73076923  8.84615385  8.96153846  9.07692308  9.19230769
  9.30769231  9.42307692  9.53846154  9.65384615  9.76923077  9.88461538
 10.        ]


In [12]:
arr3.shape

(11,)

In [13]:
arr3.ndim

1

In [14]:
arr3.size

11

In [15]:
arr3.dtype

dtype('int64')

In [17]:
arr2[1,0,1]

np.float64(0.0)

In [18]:
np.sum(arr2)

np.float64(0.0)

In [20]:
arr5=np.ones((3,5))
arr5[2,1]=25
arr5[1,2]=36
np.prod(arr5)

np.float64(900.0)

In [23]:
arr6 = np.arange(1,21)
even_num = arr[arr6%2==0]
print(even_num)
odd_num = arr[arr6%2 != 0]
print(odd_num)

[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [39]:
arr7=np.array([1,2,3,4,5,6,7])
print(arr7.shape)
arr7=arr7.reshape(7,1)
print(arr7)

(7,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [47]:
marks=np.array([33,22,34,66,90])
print(marks[marks>=33])
               

[33 34 66 90]
